---
title: "ProjectProposal"
author: "Ohene Akuoko, Kelsie Ferin, Kati Togliatti & Victoria Walker"
output: html_document
---

## Background: Kelsie
  + What problem are you addressing? Why is there a need for this project?
  + Where does your data come from? Do you already have access to it? What do your data look like?
  
## Objective: Kati
  + What will "success" look like for your project?
  + You may need more than one.
  + Potentially consider objectives for this class, as well as long term (if necessary)
  
## Approach: Victoria
  + What strategies and tools will you use to reach your objective?
  
## Desired outcome: Ohene
  + What does the final product look like?
  
  The end result of our project would be a complete functioning and viable relational database.This relational database will provide an ordered and organized environment that will improve the knowledge and the understanding of the relationships of various soil-plant-atmoshere relationships. This database will allow public and private users to better understand and grasp the vastness of the 6 different weaher datasets and parameters. This will in turn allow for users to excersice specific data queries for their personal, research or corporate use. The database will also give order and further understanding to the  manager and developers as well, to allow better handling of the data along with a more desireable environment to clean, update and query newer data as it comes in.

  + "Explain how we will attempt to share our results or the end product of this data.[speak about WWIlLL when we hae this relational database together and ready to go."
  "related to our question, what do we wxpect the relational database to look like and what will it do how will this database perform up toscalebased on what we desire for it to do.."
  " Also can include an analysis of any impacts that this will have to Kaiti's individual project and beyond at the larger scale.."
  
## Timeline: 
  + Use an additional page to create a timeline. Use the timeline to describe deliverables that will be held accountable within your group. Consider creating tasks that are easily assignable within the group, with clear deadlines.

